[versions]
agp = "8.10.1"
androidAsyncHttp = "1.4.11"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
okhttp = "4.12.0"
appauth = "0.11.1"
livekitAndroid = "2.12.2"
hivemqMqttClient = "1.3.0"
nettyCodecHttp2 = "4.1.100.Final"
nettyHandler = "4.1.100.Final"
localbroadcastmanager = "1.1.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"

[libraries]
android-async-http = { module = "com.loopj.android:android-async-http", version.ref = "androidAsyncHttp" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
appauth = { module = "net.openid:appauth", version.ref = "appauth" }
livekit-android = { module = "io.livekit:livekit-android", version.ref = "livekitAndroid" }
hivemq-mqtt-client = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemqMqttClient" }
netty-codec-http2 = { module = "io.netty:netty-codec-http2", version.ref = "nettyCodecHttp2" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "nettyHandler" }
localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "localbroadcastmanager" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

